"use client"

import * as React from "react"
import { useParams, useSearchParams } from "next/navigation"
import { AuthenticatedLayout } from "@/components/layouts"
import { BinaryMarketView, VersusMarketView, MultiOptionMarketView } from "@/components/parent/market-details"
import type { BinaryMarketData, VersusMarketData, MultiOptionMarketData } from "@/components/parent/market-details"

export default function MarketDetailPage() {
  const params = useParams()
  const searchParams = useSearchParams()

  const marketId = (params?.id as string) || "1"
  const forcedType = searchParams?.get("type")

  // Mock dataset for multi-option markets (Figma: Who would be Evicted First ??)
  const mockMultiOptionMarket: MultiOptionMarketData = {
    id: marketId,
    title: "Who would be Evicted First ??",
    category: "EVICTION",
    totalTradesVolume: "₦ 250,000",
    rules:
      "This is the market rule generated for each individula markets and there id this would be generated by us",
    candidates: [
      { id: "m1", name: "Mercy", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m2", name: "Ivana", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m3", name: "Pere", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m4", name: "CeeC", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m5", name: "Seyi", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m6", name: "Ilebaye", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m7", name: "Alex", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m8", name: "Cross", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m9", name: "Adekunle", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
      { id: "m10", name: "Venita", avatarUrl: "/testimg.png", tradesVolume: "₦667k", yesOddsText: "1k → 3k", noOddsText: "1k → 3k", yesPrice: 0.33, noPrice: 0.33 },
    ],
    tradeHistory: [
      { id: "mo1", shares: 200, outcome: "yes", candidateName: "Mercy", timestamp: "5 Mins ago" },
      { id: "mo2", shares: 200, outcome: "yes", candidateName: "Mercy", timestamp: "5 Mins ago" },
      { id: "mo3", shares: 200, outcome: "yes", candidateName: "Mercy", timestamp: "5 Mins ago" },
      { id: "mo4", shares: 200, outcome: "yes", candidateName: "Mercy", timestamp: "5 Mins ago" },
      { id: "mo5", shares: 200, outcome: "yes", candidateName: "Mercy", timestamp: "5 Mins ago" },
    ],
    userPosition: null,
  }

  // Mock dataset for 1v1 matchup markets (Figma: Mercy vs Ivana)
  const mockVersusMarket: VersusMarketData = {
    id: marketId,
    title: "Would Mercy Slap Ivana??",
    category: "HOH",
    rules:
      "This is the market rule generated for each individula markets and there id this would be generated by us",
    player1: {
      id: "p1",
      name: "Mercy",
      avatarUrl: "/testimg.png",
      probability: 50,
      yesOddsText: "1k → 3k",
      noOddsText: "1k → 5k",
      yesPrice: 0.33,
      noPrice: 0.20,
    },
    player2: {
      id: "p2",
      name: "Ivana",
      avatarUrl: "/testimg.png",
      probability: 50,
      yesOddsText: "1k → 3k",
      noOddsText: "1k → 5k",
      yesPrice: 0.33,
      noPrice: 0.20,
    },
    tradeHistory: [
      { id: "v1", shares: 200, outcome: "yes", playerName: "Mercy", timestamp: "5 Mins ago" },
      { id: "v2", shares: 200, outcome: "yes", playerName: "Mercy", timestamp: "5 Mins ago" },
      { id: "v3", shares: 200, outcome: "yes", playerName: "Mercy", timestamp: "5 Mins ago" },
      { id: "v4", shares: 200, outcome: "yes", playerName: "Mercy", timestamp: "5 Mins ago" },
    ],
    userPosition: null,
  }

  // Mock dataset for standard binary markets
  const mockBinaryMarket: BinaryMarketData = {
    id: marketId,
    title: "Will a Female Housemate win HoH this week?",
    category: "HOH",
    rules:
      "This is the market rule generated for each individula markets and there id this would be generated by us",
    yesProbability: 50,
    noProbability: 50,
    yesOddsText: "1k → 3k",
    noOddsText: "1k → 5k",
    yesPrice: 0.33,
    noPrice: 0.20,
    tradeHistory: [
      { id: "b1", shares: 200, outcome: "yes", timestamp: "5 Mins ago" },
      { id: "b2", shares: 200, outcome: "yes", timestamp: "5 Mins ago" },
      { id: "b3", shares: 200, outcome: "yes", timestamp: "5 Mins ago" },
      { id: "b4", shares: 200, outcome: "yes", timestamp: "5 Mins ago" },
      { id: "b5", shares: 200, outcome: "yes", timestamp: "5 Mins ago" },
    ],
    userPosition: null,
  }

  // Determine market type:
  // - IDs "7", "8" or type "multi_option" / "multi" -> MultiOptionMarketView
  // - IDs "4", "5", "6" or type "1v1" / "versus" -> VersusMarketView
  // - Otherwise -> BinaryMarketView
  const isMultiOptionMarket =
    forcedType === "multi_option" ||
    forcedType === "multi" ||
    marketId === "7" ||
    marketId === "8" ||
    marketId.includes("multi")

  const is1v1Market =
    !isMultiOptionMarket &&
    (forcedType === "1v1" ||
      forcedType === "versus" ||
      marketId === "4" ||
      marketId === "5" ||
      marketId === "6" ||
      marketId.includes("versus"))

  return (
    <AuthenticatedLayout>
      {isMultiOptionMarket ? (
        <MultiOptionMarketView market={mockMultiOptionMarket} />
      ) : is1v1Market ? (
        <VersusMarketView market={mockVersusMarket} />
      ) : (
        <BinaryMarketView market={mockBinaryMarket} />
      )}
    </AuthenticatedLayout>
  )
}
